### ISSUE TITLE
Databinding not working in IDE on TextBoxW

### ISSUE THREAD

**Issue by NBechtloff** [Kr00l/VBCCR#17]
There is a problem that a Textbox bound to a Datasource does not update the Datasource properly if the Textbox loses focus by clicking on another control - leaving the Textbox with Tab Key works. This only happens in the IDE, in the compiled .exe it works.
I am using the VBCCR16.ocx but I assume its also a problem in VBCCR17. Maybe other controls are affected by this too.

The problem is easy to reproduce:
Create a new exe project.
Place two textboxes on the form.
Add a reference to ADODB.
Place the following code in Form_Load:
    Dim Data As ADODB.Recordset
    Set Data = New ADODB.Recordset
    Data.Fields.Append "aString", adVarChar, 25
    Data.Open , , adOpenStatic, adLockBatchOptimistic
    Data.AddNew Array("aString"), Array("123")
    Data.UpdateBatch
    
    TextBoxW1.DataField = "aString"
    TextBoxW2.DataField = "aString"
    Set TextBoxW1.DataSource = Data
    Set TextBoxW2.DataSource = Data

If you run the program in the IDE and change the text in one textbox and tab away the other textbox's text changes.
If you instead click on the other textbox its text is not updating (the underlying datasource is not updated).

**Comment by Kr00l** [comment]
I can replicate the issue (IDE not working but working compiled)
To be honest - I have no clue why exactly.

I just could replicate it with the VB.TextBox and having CausesValidation = False. But then it does not work with click nor tab key.
Your problem is it works not with the VBCCR.TextBoxW though CausesValidation = True. Then only the click does not work.
When compiled it does work.. hmmm...

I can't help. Sorry
