### ISSUE TITLE
Circular reference when using imagelists?

### ISSUE THREAD

**Issue by NBechtloff** [Kr00l/VBCCR#2]
Hi,
control which use an imagelist (e.g. TabStrip, Listview) do not unload properly when imagelist is set from the property page designer.
I use several custom controls and the UserControl_Terminate() event is never raised. This becomes a real problem if these custom controls are not placed on your main form, because they leak GDI handles.
My workaround at the moment is setting the imagelist per property at runtime e.g. in UserControl_Initialize:
myListView.Icons = myImagelist.object.
Then everything works fine.
I tried to locate the problem in the source but no chance.
By the way great controls! Keep up the good work.

Forgot to mention: I use the ocx library.

**Comment by Kr00l** [comment]
thanks for your comment. I found already the solution for this problem. To store a pointer to the image list reference instead of the object itself. This type of indirect referencing is already done for buddy control properties in the FontCombo, Pager control etc.
However, this kind of indirect referencing was not done for image lists. I can fix this next week.
