### ISSUE TITLE
Cannot set LvwListItem Key

### ISSUE THREAD

**Issue by wardjk** [Kr00l/VBCCR#8]
I tried the VBCCR16 ListView as a nearly drop-in replacement for the ComctlLib ListView but discovered that whereas the ComctlLib ListItem Key is read/write, the LvwListItem Key is read-only. Is there a reason it is not read/write?

**Comment by Kr00l** [comment]
To be honest. I didn't know that ComctlLib ListItem Key is read/write..
The reason is because the underlying Collection's (ListItems) key is also read-only.
Of course this could be changed by removing and replacing the part. The ObjPtr would even be still the same. So no big deal actually to change it.
However, that would be a compatibility break and only available on 1.7...
What's the reason to change the key? Normally a key is a key and should stay the same.

**Comment by wardjk** [comment]
Thanks for considering it. It would help make a drop-in replacement easier with code that uses a common routine to load ListViews from RecordSets and the calling routines set the keys to have IDs for lookup later that don't match the index. The tags are sometimes used for purposes other than matching to a unique record. The loading routine doesn't know or care about fields that might uniquely identify the record or listitem and leaves it up to the calling routines if they want to set keys to something meaningful and by then the listitems already exist.

**Comment by Kr00l** [comment]
I will check to fix it. However, for the time being, for VBCCR16, you could stick to Comctlib or do a workaround. Thanks for reporting.

**Comment by Kr00l** [comment]
I checked and it doesn't break compatibility. So I could include it in VBCCR16. Good!

**Comment by Kr00l** [comment]
Update released for VBCCR16. It is now possible to change the keys of the ListView.ListItems. It seems that other controls should also be enhanced. I will commit the change to the other ones soon step-by-step. However, for your immediate issue this should be solved. Thanks

**Comment by wardjk** [comment]
That's great! Thanks for doing this!
